version: '3.4'

services:
  images_scrape:
    image: ${DOCKER_REGISTRY-}imagesscrape
    build:
      context: .
      dockerfile: src/ImagesScrape/Dockerfile
  images_export:
    image: ${DOCKER_REGISTRY-}imagesexport
    build:
      context: .
      dockerfile: src/ImagesExport/Dockerfile
  images_collect:
    image: ${DOCKER_REGISTRY-}imagescollect
    build:
      context: .
      dockerfile: src/ImagesCollect/Dockerfile