version: '3.4'

services:

  s21e_images:
    image: ${DOCKER_REGISTRY-}s21eimages
    container_name: s21e_images
    build:
      context: .
      dockerfile: S21eImages/Dockerfile
    ports:
      - 3306:3306
    environment:
       - MYSQL_HOST
       - MYSQL_USER
       - MYSQL_PASSWORD
       - DATA_PATH
       - ASSETS_PATH
       - RANGE